[supabase]
url = "https://ejvzdfnspcwcazltweig.supabase.co"
key = "your-anon-key"
service_role_key = "your-service-role-key"

OPENAI_API_KEY = "sk-your-actual-api-key-here"
OPENAI_MODEL = "gpt-3.5-turbo"
MAX_TOKENS = "2000"
TEMPERATURE = "0.7"

[admin]
default_email = "admin@example.com"
default_password = "SuperStrongPassword123!"
