[supabase]
url = "https://ejvzdfnspcwcazltweig.supabase.co"
anon_key = "your-anon-key"
service_role_key = "your-service-role-key"

[openai]
api_key = "sk-your-api-key-here"
model = "gpt-3.5-turbo"
max_tokens = 2000
temperature = 0.7
