[supabase]
url = "https://abcd1234efgh.supabase.co"
key = "YOUR-ANON-KEY"
service_role_key = "YOUR-SERVICE-ROLE-KEY"

[admin]
default_email = "admin@example.com"
default_password = "SuperStrongPassword123!"
