[supabase]
url = "https://your-project-ref.supabase.co"
key = "your-anon-key"
service_role_key = "your-service-role-key"


[admin]
default_email = "admin@example.com"
default_password = "SuperStrongPassword123!"
