[supabase]
url = "https://ejvzdfnspcwcazltweig.supabase.co"
key = "your-anon-key"
service_role_key = "your-service-role-key"

OPENAI_API_KEY = "sk-your-api-key-here"

[admin]
default_email = "admin@example.com"
default_password = "SuperStrongPassword123!"
