[supabase]
url = "https://ejvzdfnspcwcazltweig.supabase.co"
key = "your-anon-key"
service_role_key = "your-service-role-key"

[openai]
api_key = "sk-REPLACE_WITH_YOUR_KEY"
model = "gpt-3.5-turbo"
max_tokens = 2000
temperature = 0.7

[admin]
default_email = "admin@example.com"
default_password = "SuperStrongPassword123!"
