# Supabase section
[supabase]
url = "https://ejvzdfnspcwcazltweig.supabase.co"
anon_key = "your-anon-key"
service_role_key = "your-service-role-key"

# OpenAI (flat key so initialize_openai() works)
OPENAI_API_KEY = "sk-your-api-key-here"
OPENAI_MODEL = "gpt-3.5-turbo"
MAX_TOKENS = 2000
TEMPERATURE = 0.7
