[supabase]
url = "https://abcd1234efgh.supabase.co"
key = "YOUR-ANON-KEY"
SUPABASE_SERVICE_ROLE_KEY = "your_service_role_key_here"

[admin]
default_email = "admin@example.com"
default_password = "SuperStrongPassword123!"
